// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace UITests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITest.Input;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WindowsRuntimeControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = Microsoft.VisualStudio.TestTools.UITest.Input.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// TestListViewButtonIsPresent - Use 'TestListViewButtonIsPresentExpectedValues' to pass parameters into this method.
        /// </summary>
        public void TestListViewButtonIsPresent()
        {
            #region Variable Declarations
            XamlListItem listViewButton = this.UICountdownWindow.SidebarMenu.ListViewButton;
            #endregion

            // Verify that the 'Exists' property of 'ListViewListBoxItem' list item equals 'True'
            Assert.AreEqual(this.TestListViewButtonIsPresentExpectedValues.ListViewButtonExists, listViewButton.Exists, "List View button does not exist");

            // Verify that the 'Enabled' property of 'ListViewListBoxItem' list item equals 'True'
            Assert.AreEqual(this.TestListViewButtonIsPresentExpectedValues.ListViewButtonEnabled, listViewButton.Enabled, "List View Button is not enabled");
        }
        
        #region Properties
        public virtual TestListViewButtonIsPresentExpectedValues TestListViewButtonIsPresentExpectedValues
        {
            get
            {
                if ((this.mTestListViewButtonIsPresentExpectedValues == null))
                {
                    this.mTestListViewButtonIsPresentExpectedValues = new TestListViewButtonIsPresentExpectedValues();
                }
                return this.mTestListViewButtonIsPresentExpectedValues;
            }
        }
        
        public UICountdownWindow UICountdownWindow
        {
            get
            {
                if ((this.mUICountdownWindow == null))
                {
                    this.mUICountdownWindow = new UICountdownWindow();
                }
                return this.mUICountdownWindow;
            }
        }
        #endregion
        
        #region Fields
        private TestListViewButtonIsPresentExpectedValues mTestListViewButtonIsPresentExpectedValues;
        
        private UICountdownWindow mUICountdownWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestListViewButtonIsPresent'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class TestListViewButtonIsPresentExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Exists' property of 'ListViewListBoxItem' list item equals 'True'
        /// </summary>
        public bool ListViewButtonExists = true;
        
        /// <summary>
        /// Verify that the 'Enabled' property of 'ListViewListBoxItem' list item equals 'True'
        /// </summary>
        public bool ListViewButtonEnabled = true;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICountdownWindow : XamlWindow
    {
        
        public UICountdownWindow()
        {
            #region Search Criteria
            this.SearchProperties[XamlControl.PropertyNames.Name] = "Countdown";
            this.SearchProperties[XamlControl.PropertyNames.ClassName] = "Windows.UI.Core.CoreWindow";
            this.WindowTitles.Add("Countdown");
            #endregion
        }
        
        #region Properties
        public SidebarMenu SidebarMenu
        {
            get
            {
                if ((this.mSidebarMenu == null))
                {
                    this.mSidebarMenu = new SidebarMenu(this);
                }
                return this.mSidebarMenu;
            }
        }
        
        public XamlList UITaskListBoxList
        {
            get
            {
                if ((this.mUITaskListBoxList == null))
                {
                    this.mUITaskListBoxList = new XamlList(this);
                    #region Search Criteria
                    this.mUITaskListBoxList.SearchProperties[XamlList.PropertyNames.AutomationId] = "TaskListBox";
                    this.mUITaskListBoxList.WindowTitles.Add("Countdown");
                    #endregion
                }
                return this.mUITaskListBoxList;
            }
        }
        #endregion
        
        #region Fields
        private SidebarMenu mSidebarMenu;
        
        private XamlList mUITaskListBoxList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class SidebarMenu : XamlList
    {
        
        public SidebarMenu(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlList.PropertyNames.AutomationId] = "MyListBox";
            this.WindowTitles.Add("Countdown");
            #endregion
        }
        
        #region Properties
        public XamlListItem ListViewButton
        {
            get
            {
                if ((this.mListViewButton == null))
                {
                    this.mListViewButton = new XamlListItem(this);
                    #region Search Criteria
                    this.mListViewButton.SearchProperties[XamlListItem.PropertyNames.AutomationId] = "ListViewListBoxItem";
                    this.mListViewButton.WindowTitles.Add("Countdown");
                    #endregion
                }
                return this.mListViewButton;
            }
        }
        #endregion
        
        #region Fields
        private XamlListItem mListViewButton;
        #endregion
    }
}
