// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace UITests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITest.Input;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.DirectUIControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WindowsRuntimeControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = Microsoft.VisualStudio.TestTools.UITest.Input.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// TestListViewButtonIsPresent - Use 'TestListViewButtonIsPresentExpectedValues' to pass parameters into this method.
        /// </summary>
        public void TestListViewButtonIsPresent()
        {
            #region Variable Declarations
            XamlListItem listViewButton = this.UICountdownWindow.SidebarMenuListBox.ListViewButton;
            #endregion

            // Verify that the 'Exists' property of 'ListViewListBoxItem' list item equals 'True'
            Assert.AreEqual(this.TestListViewButtonIsPresentExpectedValues.ListViewButtonExists, listViewButton.Exists, "List View button does not exist");

            // Verify that the 'Enabled' property of 'ListViewListBoxItem' list item equals 'True'
            Assert.AreEqual(this.TestListViewButtonIsPresentExpectedValues.ListViewButtonEnabled, listViewButton.Enabled, "List View Button is not enabled");
        }
        
        #region Properties
        public virtual TestListViewButtonIsPresentExpectedValues TestListViewButtonIsPresentExpectedValues
        {
            get
            {
                if ((this.mTestListViewButtonIsPresentExpectedValues == null))
                {
                    this.mTestListViewButtonIsPresentExpectedValues = new TestListViewButtonIsPresentExpectedValues();
                }
                return this.mTestListViewButtonIsPresentExpectedValues;
            }
        }
        
        public UICountdownWindow UICountdownWindow
        {
            get
            {
                if ((this.mUICountdownWindow == null))
                {
                    this.mUICountdownWindow = new UICountdownWindow();
                }
                return this.mUICountdownWindow;
            }
        }
        
        public ErrorWindow ErrorWindow
        {
            get
            {
                if ((this.mErrorWindow == null))
                {
                    this.mErrorWindow = new ErrorWindow();
                }
                return this.mErrorWindow;
            }
        }
        #endregion
        
        #region Fields
        private TestListViewButtonIsPresentExpectedValues mTestListViewButtonIsPresentExpectedValues;
        
        private UICountdownWindow mUICountdownWindow;
        
        private ErrorWindow mErrorWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestListViewButtonIsPresent'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class TestListViewButtonIsPresentExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Exists' property of 'ListViewListBoxItem' list item equals 'True'
        /// </summary>
        public bool ListViewButtonExists = true;
        
        /// <summary>
        /// Verify that the 'Enabled' property of 'ListViewListBoxItem' list item equals 'True'
        /// </summary>
        public bool ListViewButtonEnabled = true;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICountdownWindow : XamlWindow
    {
        
        public UICountdownWindow()
        {
            #region Search Criteria
            this.SearchProperties[XamlControl.PropertyNames.Name] = "Countdown";
            this.SearchProperties[XamlControl.PropertyNames.ClassName] = "Windows.UI.Core.CoreWindow";
            this.WindowTitles.Add("Countdown");
            #endregion
        }
        
        #region Properties
        public SidebarMenuListBox SidebarMenuListBox
        {
            get
            {
                if ((this.mSidebarMenuListBox == null))
                {
                    this.mSidebarMenuListBox = new SidebarMenuListBox(this);
                }
                return this.mSidebarMenuListBox;
            }
        }
        
        public TaskListBox TaskListBox
        {
            get
            {
                if ((this.mTaskListBox == null))
                {
                    this.mTaskListBox = new TaskListBox(this);
                }
                return this.mTaskListBox;
            }
        }
        
        public UIMyCommandBarCustom UIMyCommandBarCustom
        {
            get
            {
                if ((this.mUIMyCommandBarCustom == null))
                {
                    this.mUIMyCommandBarCustom = new UIMyCommandBarCustom(this);
                }
                return this.mUIMyCommandBarCustom;
            }
        }
        
        public XamlControl MyCalendar
        {
            get
            {
                if ((this.mMyCalendar == null))
                {
                    this.mMyCalendar = new XamlControl(this);
                    #region Search Criteria
                    this.mMyCalendar.SearchProperties[UITestControl.PropertyNames.ControlType] = "Calendar";
                    this.mMyCalendar.SearchProperties["AutomationId"] = "MyCalendar";
                    this.mMyCalendar.WindowTitles.Add("Countdown");
                    #endregion
                }
                return this.mMyCalendar;
            }
        }
        
        public UIContentScrollViewerPane UIContentScrollViewerPane
        {
            get
            {
                if ((this.mUIContentScrollViewerPane == null))
                {
                    this.mUIContentScrollViewerPane = new UIContentScrollViewerPane(this);
                }
                return this.mUIContentScrollViewerPane;
            }
        }
        
        public UIDatepickerGroup UIDatepickerGroup
        {
            get
            {
                if ((this.mUIDatepickerGroup == null))
                {
                    this.mUIDatepickerGroup = new UIDatepickerGroup(this);
                }
                return this.mUIDatepickerGroup;
            }
        }
        
        public UITimepickerGroup UITimepickerGroup
        {
            get
            {
                if ((this.mUITimepickerGroup == null))
                {
                    this.mUITimepickerGroup = new UITimepickerGroup(this);
                }
                return this.mUITimepickerGroup;
            }
        }
        
        public UIAddTaskWindow UIAddTaskWindow
        {
            get
            {
                if ((this.mUIAddTaskWindow == null))
                {
                    this.mUIAddTaskWindow = new UIAddTaskWindow(this);
                }
                return this.mUIAddTaskWindow;
            }
        }
        
        public XamlButton HamburgerButton
        {
            get
            {
                if ((this.mHamburgerButton == null))
                {
                    this.mHamburgerButton = new XamlButton(this);
                    #region Search Criteria
                    this.mHamburgerButton.SearchProperties[XamlButton.PropertyNames.AutomationId] = "HamburgerButton";
                    this.mHamburgerButton.WindowTitles.Add("Countdown");
                    #endregion
                }
                return this.mHamburgerButton;
            }
        }
        
        public UIPaneRootWindow UIPaneRootWindow
        {
            get
            {
                if ((this.mUIPaneRootWindow == null))
                {
                    this.mUIPaneRootWindow = new UIPaneRootWindow(this);
                }
                return this.mUIPaneRootWindow;
            }
        }
        
        public XamlText DetailedViewTaskName
        {
            get
            {
                if ((this.mDetailedViewTaskName == null))
                {
                    this.mDetailedViewTaskName = new XamlText(this);
                    #region Search Criteria
                    this.mDetailedViewTaskName.SearchProperties[XamlText.PropertyNames.Name] = "Task Name: Sample Task";
                    this.mDetailedViewTaskName.WindowTitles.Add("Countdown");
                    #endregion
                }
                return this.mDetailedViewTaskName;
            }
        }
        
        public XamlText DetailedViewDescription
        {
            get
            {
                if ((this.mDetailedViewDescription == null))
                {
                    this.mDetailedViewDescription = new XamlText(this);
                    #region Search Criteria
                    this.mDetailedViewDescription.SearchProperties[XamlText.PropertyNames.Name] = "Description: Sample Description";
                    this.mDetailedViewDescription.WindowTitles.Add("Countdown");
                    #endregion
                }
                return this.mDetailedViewDescription;
            }
        }
        
        public DeleteTaskList DeleteTaskList
        {
            get
            {
                if ((this.mDeleteTaskList == null))
                {
                    this.mDeleteTaskList = new DeleteTaskList(this);
                }
                return this.mDeleteTaskList;
            }
        }
        
        public RemoveTaskDialog RemoveTaskDialog
        {
            get
            {
                if ((this.mRemoveTaskDialog == null))
                {
                    this.mRemoveTaskDialog = new RemoveTaskDialog(this);
                }
                return this.mRemoveTaskDialog;
            }
        }
        
        public UIDeleteWindow UIDeleteWindow
        {
            get
            {
                if ((this.mUIDeleteWindow == null))
                {
                    this.mUIDeleteWindow = new UIDeleteWindow(this);
                }
                return this.mUIDeleteWindow;
            }
        }
        
        public UISearchBar UISearchBar
        {
            get
            {
                if ((this.mUISearchBar == null))
                {
                    this.mUISearchBar = new UISearchBar(this);
                }
                return this.mUISearchBar;
            }
        }
        #endregion
        
        #region Fields
        private SidebarMenuListBox mSidebarMenuListBox;
        
        private TaskListBox mTaskListBox;
        
        private UIMyCommandBarCustom mUIMyCommandBarCustom;
        
        private XamlControl mMyCalendar;
        
        private UIContentScrollViewerPane mUIContentScrollViewerPane;
        
        private UIDatepickerGroup mUIDatepickerGroup;
        
        private UITimepickerGroup mUITimepickerGroup;
        
        private UIAddTaskWindow mUIAddTaskWindow;
        
        private XamlButton mHamburgerButton;
        
        private UIPaneRootWindow mUIPaneRootWindow;
        
        private XamlText mDetailedViewTaskName;
        
        private XamlText mDetailedViewDescription;
        
        private DeleteTaskList mDeleteTaskList;
        
        private RemoveTaskDialog mRemoveTaskDialog;
        
        private UIDeleteWindow mUIDeleteWindow;
        
        private UISearchBar mUISearchBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class SidebarMenuListBox : XamlList
    {
        
        public SidebarMenuListBox(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlList.PropertyNames.AutomationId] = "MyListBox";
            this.WindowTitles.Add("Countdown");
            #endregion
        }
        
        #region Properties
        public XamlListItem ListViewButton
        {
            get
            {
                if ((this.mListViewButton == null))
                {
                    this.mListViewButton = new XamlListItem(this);
                    #region Search Criteria
                    this.mListViewButton.SearchProperties[XamlListItem.PropertyNames.AutomationId] = "ListViewListBoxItem";
                    this.mListViewButton.WindowTitles.Add("Countdown");
                    #endregion
                }
                return this.mListViewButton;
            }
        }
        
        public XamlListItem CalendarViewButton
        {
            get
            {
                if ((this.mCalendarViewButton == null))
                {
                    this.mCalendarViewButton = new XamlListItem(this);
                    #region Search Criteria
                    this.mCalendarViewButton.SearchProperties[XamlListItem.PropertyNames.AutomationId] = "CalendarViewListBoxItem";
                    this.mCalendarViewButton.WindowTitles.Add("Countdown");
                    #endregion
                }
                return this.mCalendarViewButton;
            }
        }
        #endregion
        
        #region Fields
        private XamlListItem mListViewButton;
        
        private XamlListItem mCalendarViewButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class TaskListBox : XamlList
    {
        
        public TaskListBox(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlList.PropertyNames.AutomationId] = "TaskListBox";
            this.WindowTitles.Add("Countdown");
            #endregion
        }
        
        #region Properties
        public XamlListItem FirstListBoxItem
        {
            get
            {
                if ((this.mFirstListBoxItem == null))
                {
                    this.mFirstListBoxItem = new XamlListItem(this);
                    #region Search Criteria
                    this.mFirstListBoxItem.SearchProperties[XamlListItem.PropertyNames.Name] = "Countdown.Networking.Serialization.Task";
                    this.mFirstListBoxItem.WindowTitles.Add("Countdown");
                    #endregion
                }
                return this.mFirstListBoxItem;
            }
        }
        #endregion
        
        #region Fields
        private XamlListItem mFirstListBoxItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMyCommandBarCustom : XamlControl
    {
        
        public UIMyCommandBarCustom(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Custom";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "ApplicationBar";
            this.SearchProperties["AutomationId"] = "MyCommandBar";
            this.WindowTitles.Add("Countdown");
            #endregion
        }
        
        #region Properties
        public XamlButton UIAddTaskButton
        {
            get
            {
                if ((this.mUIAddTaskButton == null))
                {
                    this.mUIAddTaskButton = new XamlButton(this);
                    #region Search Criteria
                    this.mUIAddTaskButton.SearchProperties[XamlButton.PropertyNames.AutomationId] = "AddButton";
                    this.mUIAddTaskButton.WindowTitles.Add("Countdown");
                    #endregion
                }
                return this.mUIAddTaskButton;
            }
        }
        
        public XamlButton UIRemoveTaskButton
        {
            get
            {
                if ((this.mUIRemoveTaskButton == null))
                {
                    this.mUIRemoveTaskButton = new XamlButton(this);
                    #region Search Criteria
                    this.mUIRemoveTaskButton.SearchProperties[XamlButton.PropertyNames.AutomationId] = "RemoveButton";
                    this.mUIRemoveTaskButton.WindowTitles.Add("Countdown");
                    #endregion
                }
                return this.mUIRemoveTaskButton;
            }
        }
        #endregion
        
        #region Fields
        private XamlButton mUIAddTaskButton;
        
        private XamlButton mUIRemoveTaskButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIContentScrollViewerPane : XamlControl
    {
        
        public UIContentScrollViewerPane(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Pane";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "ScrollViewer";
            this.SearchProperties["AutomationId"] = "ContentScrollViewer";
            this.WindowTitles.Add("Countdown");
            #endregion
        }
        
        #region Properties
        public UITaskNameText UITaskNameText
        {
            get
            {
                if ((this.mUITaskNameText == null))
                {
                    this.mUITaskNameText = new UITaskNameText(this);
                }
                return this.mUITaskNameText;
            }
        }
        
        public UIDescriptionText UIDescriptionText
        {
            get
            {
                if ((this.mUIDescriptionText == null))
                {
                    this.mUIDescriptionText = new UIDescriptionText(this);
                }
                return this.mUIDescriptionText;
            }
        }
        
        public XamlText NoTasksToDeleteText
        {
            get
            {
                if ((this.mNoTasksToDeleteText == null))
                {
                    this.mNoTasksToDeleteText = new XamlText(this);
                    #region Search Criteria
                    this.mNoTasksToDeleteText.SearchProperties[XamlText.PropertyNames.Name] = "No Tasks to delete";
                    this.mNoTasksToDeleteText.WindowTitles.Add("Countdown");
                    #endregion
                }
                return this.mNoTasksToDeleteText;
            }
        }
        
        public XamlText NoTaskSelectedText
        {
            get
            {
                if ((this.mNoTaskSelectedText == null))
                {
                    this.mNoTaskSelectedText = new XamlText(this);
                    #region Search Criteria
                    this.mNoTaskSelectedText.SearchProperties[XamlText.PropertyNames.Name] = "No task selected";
                    this.mNoTaskSelectedText.WindowTitles.Add("Countdown");
                    #endregion
                }
                return this.mNoTaskSelectedText;
            }
        }
        #endregion
        
        #region Fields
        private UITaskNameText mUITaskNameText;
        
        private UIDescriptionText mUIDescriptionText;
        
        private XamlText mNoTasksToDeleteText;
        
        private XamlText mNoTaskSelectedText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITaskNameText : XamlText
    {
        
        public UITaskNameText(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlText.PropertyNames.Name] = "Task Name";
            this.WindowTitles.Add("Countdown");
            #endregion
        }
        
        #region Properties
        public XamlEdit AddTaskTextBox
        {
            get
            {
                if ((this.mAddTaskTextBox == null))
                {
                    this.mAddTaskTextBox = new XamlEdit(this);
                    #region Search Criteria
                    this.mAddTaskTextBox.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mAddTaskTextBox.WindowTitles.Add("Countdown");
                    #endregion
                }
                return this.mAddTaskTextBox;
            }
        }
        #endregion
        
        #region Fields
        private XamlEdit mAddTaskTextBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDescriptionText : XamlText
    {
        
        public UIDescriptionText(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlText.PropertyNames.Name] = "Description";
            this.WindowTitles.Add("Countdown");
            #endregion
        }
        
        #region Properties
        public XamlEdit DescriptionTextBox
        {
            get
            {
                if ((this.mDescriptionTextBox == null))
                {
                    this.mDescriptionTextBox = new XamlEdit(this);
                    #region Search Criteria
                    this.mDescriptionTextBox.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mDescriptionTextBox.WindowTitles.Add("Countdown");
                    #endregion
                }
                return this.mDescriptionTextBox;
            }
        }
        #endregion
        
        #region Fields
        private XamlEdit mDescriptionTextBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDatepickerGroup : XamlControl
    {
        
        public UIDatepickerGroup(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Group";
            this.SearchProperties[UITestControl.PropertyNames.Name] = "date picker";
            this.WindowTitles.Add("Countdown");
            #endregion
        }
        
        #region Properties
        public XamlButton DueDateDatePicker
        {
            get
            {
                if ((this.mDueDateDatePicker == null))
                {
                    this.mDueDateDatePicker = new XamlButton(this);
                    #region Search Criteria
                    this.mDueDateDatePicker.SearchProperties[XamlButton.PropertyNames.AutomationId] = "FlyoutButton";
                    this.mDueDateDatePicker.WindowTitles.Add("Countdown");
                    #endregion
                }
                return this.mDueDateDatePicker;
            }
        }
        #endregion
        
        #region Fields
        private XamlButton mDueDateDatePicker;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITimepickerGroup : XamlControl
    {
        
        public UITimepickerGroup(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Group";
            this.SearchProperties[UITestControl.PropertyNames.Name] = "time picker";
            this.WindowTitles.Add("Countdown");
            #endregion
        }
        
        #region Properties
        public XamlButton DueDateTimePicker
        {
            get
            {
                if ((this.mDueDateTimePicker == null))
                {
                    this.mDueDateTimePicker = new XamlButton(this);
                    #region Search Criteria
                    this.mDueDateTimePicker.SearchProperties[XamlButton.PropertyNames.AutomationId] = "FlyoutButton";
                    this.mDueDateTimePicker.WindowTitles.Add("Countdown");
                    #endregion
                }
                return this.mDueDateTimePicker;
            }
        }
        #endregion
        
        #region Fields
        private XamlButton mDueDateTimePicker;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIAddTaskWindow : XamlWindow
    {
        
        public UIAddTaskWindow(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlControl.PropertyNames.Name] = "Add Task";
            this.WindowTitles.Add("Countdown");
            #endregion
        }
        
        #region Properties
        public XamlButton AddTaskAddButton
        {
            get
            {
                if ((this.mAddTaskAddButton == null))
                {
                    this.mAddTaskAddButton = new XamlButton(this);
                    #region Search Criteria
                    this.mAddTaskAddButton.SearchProperties[XamlButton.PropertyNames.Name] = "Add";
                    this.mAddTaskAddButton.WindowTitles.Add("Countdown");
                    #endregion
                }
                return this.mAddTaskAddButton;
            }
        }
        
        public XamlButton AddTaskCancelButton
        {
            get
            {
                if ((this.mAddTaskCancelButton == null))
                {
                    this.mAddTaskCancelButton = new XamlButton(this);
                    #region Search Criteria
                    this.mAddTaskCancelButton.SearchProperties[XamlButton.PropertyNames.Name] = "Cancel";
                    this.mAddTaskCancelButton.WindowTitles.Add("Countdown");
                    #endregion
                }
                return this.mAddTaskCancelButton;
            }
        }
        #endregion
        
        #region Fields
        private XamlButton mAddTaskAddButton;
        
        private XamlButton mAddTaskCancelButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIPaneRootWindow : XamlWindow
    {
        
        public UIPaneRootWindow(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlControl.PropertyNames.AutomationId] = "PaneRoot";
            this.WindowTitles.Add("Countdown");
            #endregion
        }
        
        #region Properties
        public XamlList UIMyListBoxList
        {
            get
            {
                if ((this.mUIMyListBoxList == null))
                {
                    this.mUIMyListBoxList = new XamlList(this);
                    #region Search Criteria
                    this.mUIMyListBoxList.SearchProperties[XamlList.PropertyNames.AutomationId] = "MyListBox";
                    this.mUIMyListBoxList.WindowTitles.Add("Countdown");
                    #endregion
                }
                return this.mUIMyListBoxList;
            }
        }
        #endregion
        
        #region Fields
        private XamlList mUIMyListBoxList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class DeleteTaskList : XamlList
    {
        
        public DeleteTaskList(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Countdown");
            #endregion
        }
        
        #region Properties
        public XamlListItem TaskToDelete
        {
            get
            {
                if ((this.mTaskToDelete == null))
                {
                    this.mTaskToDelete = new XamlListItem(this);
                    #region Search Criteria
                    this.mTaskToDelete.SearchProperties[XamlListItem.PropertyNames.Name] = "Sample Task";
                    this.mTaskToDelete.WindowTitles.Add("Countdown");
                    #endregion
                }
                return this.mTaskToDelete;
            }
        }
        #endregion
        
        #region Fields
        private XamlListItem mTaskToDelete;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class RemoveTaskDialog : XamlWindow
    {
        
        public RemoveTaskDialog(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlControl.PropertyNames.Name] = "Remove Task";
            this.WindowTitles.Add("Countdown");
            #endregion
        }
        
        #region Properties
        public XamlButton DeleteTaskButton
        {
            get
            {
                if ((this.mDeleteTaskButton == null))
                {
                    this.mDeleteTaskButton = new XamlButton(this);
                    #region Search Criteria
                    this.mDeleteTaskButton.SearchProperties[XamlButton.PropertyNames.Name] = "Delete";
                    this.mDeleteTaskButton.WindowTitles.Add("Countdown");
                    #endregion
                }
                return this.mDeleteTaskButton;
            }
        }
        #endregion
        
        #region Fields
        private XamlButton mDeleteTaskButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDeleteWindow : XamlWindow
    {
        
        public UIDeleteWindow(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlControl.PropertyNames.Name] = "Delete";
            this.WindowTitles.Add("Countdown");
            #endregion
        }
        
        #region Properties
        public XamlButton UIYesButton
        {
            get
            {
                if ((this.mUIYesButton == null))
                {
                    this.mUIYesButton = new XamlButton(this);
                    #region Search Criteria
                    this.mUIYesButton.SearchProperties[XamlButton.PropertyNames.Name] = "Yes";
                    this.mUIYesButton.WindowTitles.Add("Countdown");
                    #endregion
                }
                return this.mUIYesButton;
            }
        }
        #endregion
        
        #region Fields
        private XamlButton mUIYesButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISearchBar : XamlControl
    {
        
        public UISearchBar(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Group";
            this.SearchProperties["AutomationId"] = "SearchBar";
            this.WindowTitles.Add("Countdown");
            #endregion
        }
        
        #region Properties
        public XamlEdit SearchBar
        {
            get
            {
                if ((this.mSearchBar == null))
                {
                    this.mSearchBar = new XamlEdit(this);
                    #region Search Criteria
                    this.mSearchBar.SearchProperties[XamlEdit.PropertyNames.AutomationId] = "TextBox";
                    this.mSearchBar.WindowTitles.Add("Countdown");
                    #endregion
                }
                return this.mSearchBar;
            }
        }
        #endregion
        
        #region Fields
        private XamlEdit mSearchBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class ErrorWindow : UITestControl
    {
        
        public ErrorWindow()
        {
            #region Search Criteria
            this.TechnologyName = "UIA";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Window";
            this.SearchProperties[UITestControl.PropertyNames.Name] = "ERROR";
            this.SearchProperties["FrameworkId"] = "Win32";
            this.WindowTitles.Add("ERROR");
            #endregion
        }
        
        #region Properties
        public ErrorWindowButtons ErrorWindowButtons
        {
            get
            {
                if ((this.mErrorWindowButtons == null))
                {
                    this.mErrorWindowButtons = new ErrorWindowButtons(this);
                }
                return this.mErrorWindowButtons;
            }
        }
        #endregion
        
        #region Fields
        private ErrorWindowButtons mErrorWindowButtons;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class ErrorWindowButtons : DirectUIControl
    {
        
        public ErrorWindowButtons(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[DirectUIControl.PropertyNames.AutomationId] = "ButtonBar";
            this.WindowTitles.Add("ERROR");
            #endregion
        }
        
        #region Properties
        public DirectUIControl CloseButton
        {
            get
            {
                if ((this.mCloseButton == null))
                {
                    this.mCloseButton = new DirectUIControl(this);
                    #region Search Criteria
                    this.mCloseButton.SearchProperties[DirectUIControl.PropertyNames.AutomationId] = "Button0";
                    this.mCloseButton.WindowTitles.Add("ERROR");
                    #endregion
                }
                return this.mCloseButton;
            }
        }
        #endregion
        
        #region Fields
        private DirectUIControl mCloseButton;
        #endregion
    }
}
